// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.windsorsolutions.pesticides.domain;

import com.windsorsolutions.pesticides.domain.PesticideApplicationEvent;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PesticideApplicationEvent_Roo_Configurable {
    
    declare @type: PesticideApplicationEvent: @Configurable;
    
}
